quarkus.http.port=8082

# Database Configuration
quarkus.datasource.db-kind=postgresql
# The environment variable QUARKUS_DATASOURCE_JDBC_URL is set in docker-compose
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Allow CORS for Angular frontend
quarkus.http.cors=true
quarkus.http.cors.origins=*
