quarkus.http.port=8081

# Database Configuration
quarkus.datasource.db-kind=postgresql
# Hibernate ORM Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Kafka Consumer Configuration
kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.cobol-errors-topic.connector=smallrye-kafka
mp.messaging.incoming.cobol-errors-topic.topic=cobol-errors-topic
mp.messaging.incoming.cobol-errors-topic.value.deserializer=com.bank.errorconsumer.dto.CobolErrorDtoDeserializer
